name = "hugo-profile"
license = "MIT"
licenselink = "https://github.com/gurusabarish/hugo-profile/blob/master/LICENSE"
description = "The fastest(100) hugo theme for personal portfolio and blog."
homepage = "https://hugo-profile.netlify.com"
tags = ["Responsive","Blog", "Portfolio", "Personal", "Minimal", "Clean", "Fast", "Single page", "Seo", "Google analytics", "100"]
features = ["Highly customizable"]
min_version = "0.68.0"

[author]
  name = "Gurusabarish"
  homepage = "https://github.com/gurusabarish"
